# Generated by Django 6.0.4 on 2026-05-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='course', max_length=100),
            preserve_default=False,
        ),
    ]
