# Generated by Django 6.0.4 on 2026-05-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='student_photos/'),
            preserve_default=False,
        ),
    ]
